[phases.setup]
nixPkgs = ["php", "git"]
cmds = ["curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"]

[phases.build]
cmds = ["composer install", "php artisan config:cache"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"